#!/usr/bin/env bash

# Install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

/bin/bash -c "$(curl -LsSf https://astral.sh/uv/install.sh | sh)

sudo apt update && sudo apt install -y stow tmux zsh
rm -f ~/.bashrc ~/.vimrc ~/.bash_aliases
stow bash
stow vim
stow tmux
stow zsh

chsh -s $(which zsh)

/home/linuxbrew/.linuxbrew/bin/brew install tree duckdb broot bat glow
