# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm app -- hyprsunset
exec-once = bash -c 'sleep 2; HOUR=$(date +%-H); if (( HOUR >= 20 || HOUR < 8 )); then hyprctl hyprsunset temperature 4000; fi'
